public class Demo3 
{
    Integer varint1;
    Integer varint2;
    Integer Varint3;
    public void setValue1(integer i)
    {
       varint1=i; 
    }
   public void setValue2(integer j)
    {
       varint2=j; 
    }
    public Integer getValue1()
    {
       return varint1; 
    }
    public Integer getValue2()
    {
        return varint2;
    }
    public Integer getaddtionValue()
    {
        return Varint3;
    }
    public void ADD()
    {
     if(varint1!=null && varint2!=null)
        {
        Varint3=varint1+varint2;
        }
        
    }
   public void Sub()
    {
     if(varint1!=null && varint2!=null)
        {
        Varint3=varint1-varint2;
        }
        
    }
    public void Mul()
    {
     if(varint1!=null && varint2!=null)
        {
        Varint3=varint1*varint2;
        }
        
    }
    }